package com.sample
 
import com.sample.DecisionTableTest.Message;
 
rule "AAAAA"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( "DRL " + myMessage + kcontext.getKnowledgeRuntime().toString());
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "BBBB"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( "DRL " + myMessage );
end
