package com.sample
 
import com.sample.MyFact;
 
rule "R1"
    when
        $fact : MyFact( a > 10 )
    then
        System.out.println("R1");
        int newValue = $fact.getA() + 10;
        $fact.setA(newValue);
        // don't update now
end

rule "R2"
    when
        $fact : MyFact( a > 15 )
    then
        System.out.println("R2");
end

rule "R3"
    no-loop
    when
        $fact : MyFact( b > 10 )
    then
        System.out.println("R3");
        int newValue = $fact.getB() + 10;
        
        modify ($fact) {setB(newValue)} // "R2" is not fired because of property reactive
        
        //$fact.setB(newValue);
        //update($fact)
end

rule "R4"
    when
        $fact : MyFact( b > 15 )
    then
        System.out.println("R4");
end