package com.sample
 
import com.sample.DroolsTest.Message;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage + kcontext.getKnowledgeRuntime().toString());
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
        //eval( (5/0) == 0)
    then
        System.out.println( myMessage );
        throw new RuntimeException("XXX");
end
