package com.sample
 
import com.sample.Person;

global java.util.List results;

rule "Dummy"
    when
    then
        System.out.println( "Dummy");
end


rule "Hello"
    when
        $p : Person( age > 10 )
    then
        System.out.println( "Hello, " + $p.getName());
        results.add("hit Hello rule");
end

rule "Hello String"
    when
        $s : String( )
    then
        System.out.println( "Hello, " + $s);
end