package com.sample
 
import com.sample.Person;
 
rule "raise salary"
    //no-loop // no-loop is not required when you use @PropertyReactive
    when
        $p : Person( age > 20 )
    then
        System.out.println("raise salary for " + $p.getName());
        int newSalary = $p.getSalary() + 500;
        
        //$p.setSalary(newSalary);
        //update($p);
        
        // modify is recommended (but update also works in this example)
        modify($p) {setSalary(newSalary)}
end

rule "high salary"
    when
        $p : Person( salary > 2000 )
    then
        System.out.println("high salary! " + $p.getName() + ", $p.getSalary() = " + $p.getSalary());
end