package com.sample
 
import com.sample.MyFact;
 
rule "R1"
    when
        $f : MyFact( strData == 10 )
    then
        System.out.println( "R1 : $f = " + $f );
end

rule "R2"
    when
        $f : MyFact( strData == 20 )
    then
        System.out.println( "R2 : $f = " + $f );
end

rule "R3"
    when
        $f : MyFact( strData == 30 )
    then
        System.out.println( "R3 : $f = " + $f );
end